# Generated by Django 4.1.5 on 2023-01-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_spent', models.DateTimeField(verbose_name='date spent')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
