# Generated by Django 4.2.10 on 2024-02-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spendings", "0005_account_spending_account"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Spending",
            new_name="Transaction",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
