# Generated by Django 4.2.10 on 2024-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendings", "0006_rename_spending_transaction_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date_spent",
            field=models.DateField(verbose_name="date created"),
        ),
    ]
