# Generated by Django 5.0.2 on 2024-02-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendings", "0007_alter_transaction_date_spent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begins_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
