# Generated by Django 5.0.2 on 2024-02-21 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spendings", "0009_estimate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="estimate",
            unique_together={("category", "budget")},
        ),
    ]
